apiVersion: v1
kind: Service
metadata:
  name: {{ include "cities-app.fullname" . }}
  labels:
    {{- include "cities-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      name: http
  selector:
    {{- include "cities-app.selectorLabels" . | nindent 4 }}
